#!/usr/bin/env python

import argparse
import json
from pathlib import Path

from jinja2 import (
    Environment,
    StrictUndefined,
    FileSystemLoader,
)


def render(data_file, template_file, output_file):
    with open(template_file, 'r') as template_fh:
        template_code = template_fh.read()

    with open(data_file, 'r') as data_fh:
        data = json.load(data_fh)

    kwargs = {
        'loader': FileSystemLoader([Path(template_file).parent]),
        'undefined': StrictUndefined,
    }
    env = Environment(**kwargs).from_string(template_code)

    with open(output_file, 'w') as output_fh:
        output_fh.write(
            env.render(data)
        )


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('data')
    parser.add_argument('template')
    parser.add_argument('output')
    return parser.parse_args()


if __name__ == '__main__':
    args = parse_args()
    render(args.data, args.template, args.output)
