# THIS FILE IS PART OF THE CYLC WORKFLOW ENGINE.
# Copyright (C) NIWA & British Crown (Met Office) & Contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


name: Status

on:
  workflow_dispatch:
  schedule:
    - cron: '35 0 * * *'
  push:
    branches:
      - 'master'
    paths:
      - 'docs/status/*'
      - '.github/workflows/status.yml'

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: configure python
        uses: actions/setup-python@v4

      - name: install
        run: pip install jinja2

      - name: update
        working-directory: docs/status
        run: python build branches.json template.md.jinja2 status.md

      - name: configure git
        uses: cylc/release-actions/configure-git@v1

      - name: push changes
        run: |
          git status
          git add -f docs/status/status.md
          git commit -m 'update status page' || exit 0
          git push origin master
